@extends('layouts.apps')

@section('content')

{{-- ==========================================
     START: Page Header + Breadcrumb
     ========================================== --}}
<div class="page-header">
    <div>
        <h1 class="page-title">Add Loan</h1>
        <p class="page-subtitle">Record a new item loan transaction</p>
    </div>

    @include('partials.breadcrumb', ['items' => [
        'Transaction' => '#',
        'Loans'       => route('peminjaman.index'),
        'Add'         => '',
    ]])
</div>
{{-- END: Page Header --}}


{{-- ==========================================
     START: Alert
     ========================================== --}}
@if($errors->any())
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <i class="bi bi-exclamation-circle"></i>
        <strong>Please fix the following errors:</strong>
        <ul class="mb-0 mt-2">
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
@endif
{{-- END: Alert --}}


{{-- ==========================================
     START: Form Card
     ========================================== --}}
<div class="row g-4 mb-4 justify-content-center">
    <div class="col-12 col-lg-8">
        <div class="card border-light shadow-sm p-4">

            <h5 class="card-title mb-4">
                <i class="bi bi-hand-index-thumb text-warning"></i> Loan Information
            </h5>

            <form action="{{ route('peminjaman.store') }}" method="POST" id="peminjamanForm">
                @csrf

                {{-- =====================
                     Auto-generated Code
                ====================== --}}
                <div class="mb-3">
                    <label class="form-label-custom">Loan Code</label>
                    <input type="text"
                           class="form-control-custom"
                           value="{{ $kode }}"
                           readonly
                           style="background:#f8f9fa;">
                    <span class="text-muted" style="font-size: 12px;">
                        Loan code is auto-generated by the system.
                    </span>
                </div>

                {{-- =====================
                     Item
                ====================== --}}
                <div class="mb-3">
                    <label for="item_id" class="form-label-custom">
                        Item <span class="text-danger">*</span>
                    </label>
                    <select name="item_id"
                            id="item_id"
                            class="form-select-custom @error('item_id') is-invalid-custom @enderror"
                            required
                            autofocus>
                        <option value="">-- Select Item --</option>
                        @foreach($barang as $b)
                            <option value="{{ $b->id }}" {{ old('item_id') == $b->id ? 'selected' : '' }}>
                                {{ $b->kode_barang }} — {{ $b->nama_barang }}
                                (Stock: {{ $b->jumlah }} {{ $b->satuan }})
                            </option>
                        @endforeach
                    </select>
                    @error('item_id')
                        <div class="form-feedback-custom invalid-custom">
                            <i class="bi bi-exclamation-circle-fill"></i> {{ $message }}
                        </div>
                    @enderror
                </div>

                {{-- =====================
                     Borrower & Unit
                ====================== --}}
                <div class="row g-3 mb-3">
                    <div class="col-12 col-md-6">
                        <label for="nama_peminjam" class="form-label-custom">
                            Borrower Name <span class="text-danger">*</span>
                        </label>
                        <input type="text"
                               name="nama_peminjam"
                               id="nama_peminjam"
                               class="form-control-custom @error('nama_peminjam') is-invalid-custom @enderror"
                               value="{{ old('nama_peminjam') }}"
                               placeholder="e.g. Budi Santoso"
                               required>
                        @error('nama_peminjam')
                            <div class="form-feedback-custom invalid-custom">
                                <i class="bi bi-exclamation-circle-fill"></i> {{ $message }}
                            </div>
                        @enderror
                    </div>

                    <div class="col-12 col-md-6">
                        <label for="kelas_atau_unit" class="form-label-custom">Class / Unit</label>
                        <input type="text"
                               name="kelas_atau_unit"
                               id="kelas_atau_unit"
                               class="form-control-custom @error('kelas_atau_unit') is-invalid-custom @enderror"
                               value="{{ old('kelas_atau_unit') }}"
                               placeholder="e.g. XII RPL 1, Teacher, Staff">
                        @error('kelas_atau_unit')
                            <div class="form-feedback-custom invalid-custom">
                                <i class="bi bi-exclamation-circle-fill"></i> {{ $message }}
                            </div>
                        @enderror
                    </div>
                </div>

                {{-- =====================
                     Dates
                ====================== --}}
                <div class="row g-3 mb-3">
                    <div class="col-12 col-md-6">
                        <label for="tanggal_pinjam" class="form-label-custom">
                            Loan Date <span class="text-danger">*</span>
                        </label>
                        <input type="date"
                               name="tanggal_pinjam"
                               id="tanggal_pinjam"
                               class="form-control-custom @error('tanggal_pinjam') is-invalid-custom @enderror"
                               value="{{ old('tanggal_pinjam', date('Y-m-d')) }}"
                               required>
                        @error('tanggal_pinjam')
                            <div class="form-feedback-custom invalid-custom">
                                <i class="bi bi-exclamation-circle-fill"></i> {{ $message }}
                            </div>
                        @enderror
                    </div>

                    <div class="col-12 col-md-6">
                        <label for="rencana_kembali" class="form-label-custom">
                            Due Date <span class="text-danger">*</span>
                        </label>
                        <input type="date"
                               name="rencana_kembali"
                               id="rencana_kembali"
                               class="form-control-custom @error('rencana_kembali') is-invalid-custom @enderror"
                               value="{{ old('rencana_kembali', date('Y-m-d', strtotime('+1 day'))) }}"
                               required>
                        @error('rencana_kembali')
                            <div class="form-feedback-custom invalid-custom">
                                <i class="bi bi-exclamation-circle-fill"></i> {{ $message }}
                            </div>
                        @else
                            <span class="text-muted" style="font-size: 12px;">
                                Must not be earlier than the loan date.
                            </span>
                        @enderror
                    </div>
                </div>

                {{-- =====================
                     Quantity
                ====================== --}}
                <div class="mb-3">
                    <label for="jumlah" class="form-label-custom">
                        Quantity <span class="text-danger">*</span>
                    </label>
                    <input type="number"
                           name="jumlah"
                           id="jumlah"
                           class="form-control-custom @error('jumlah') is-invalid-custom @enderror"
                           value="{{ old('jumlah', 1) }}"
                           min="1"
                           required>
                    @error('jumlah')
                        <div class="form-feedback-custom invalid-custom">
                            <i class="bi bi-exclamation-circle-fill"></i> {{ $message }}
                        </div>
                    @else
                        <span class="text-muted" style="font-size: 12px;">
                            Stock will be <strong>reduced</strong> during the loan period.
                        </span>
                    @enderror
                </div>

                {{-- =====================
                     Notes
                ====================== --}}
                <div class="mb-3">
                    <label for="keterangan" class="form-label-custom">Notes</label>
                    <textarea name="keterangan"
                              id="keterangan"
                              rows="3"
                              class="form-control-custom @error('keterangan') is-invalid-custom @enderror"
                              placeholder="Optional notes about this loan...">{{ old('keterangan') }}</textarea>
                    @error('keterangan')
                        <div class="form-feedback-custom invalid-custom">
                            <i class="bi bi-exclamation-circle-fill"></i> {{ $message }}
                        </div>
                    @enderror
                </div>

                <hr class="my-4">

                {{-- Action Buttons --}}
                <div class="d-flex justify-content-between align-items-center">
                    <a href="{{ route('peminjaman.index') }}" class="btn-table-action">
                        <i class="bi bi-arrow-left"></i> Back
                    </a>
                    <button type="submit" class="btn-table-action btn-primary-action">
                        <i class="bi bi-check-lg"></i> Save Loan
                    </button>
                </div>

            </form>
        </div>
    </div>

    {{-- Side Info Panel --}}
    <div class="col-12 col-lg-4">
        <div class="card border-light shadow-sm p-4 h-100">
            <h5 class="card-title mb-4">
                <i class="bi bi-info-circle text-primary"></i> Guidelines
            </h5>

            <div class="mb-3">
                <div class="d-flex align-items-start">
                    <div class="me-2" style="color:#f59e0b;">
                        <i class="bi bi-exclamation-circle-fill"></i>
                    </div>
                    <div>
                        <div style="font-size: 13px; font-weight:600; color:#072F1F;">Stock will decrease</div>
                        <div class="text-muted" style="font-size:12px;">
                            Stock is <strong>reduced</strong> during the loan and restored upon return.
                        </div>
                    </div>
                </div>
            </div>

            <div class="mb-3">
                <div class="d-flex align-items-start">
                    <div class="me-2" style="color:#f59e0b;">
                        <i class="bi bi-exclamation-triangle-fill"></i>
                    </div>
                    <div>
                        <div style="font-size: 13px; font-weight:600; color:#072F1F;">Stock validation</div>
                        <div class="text-muted" style="font-size:12px;">
                            Quantity cannot exceed available stock. The system will reject invalid input.
                        </div>
                    </div>
                </div>
            </div>

            <div class="mb-3">
                <div class="d-flex align-items-start">
                    <div class="me-2" style="color:#0ea5e9;">
                        <i class="bi bi-calendar-check-fill"></i>
                    </div>
                    <div>
                        <div style="font-size: 13px; font-weight:600; color:#072F1F;">Due date monitoring</div>
                        <div class="text-muted" style="font-size:12px;">
                            Overdue loans will be highlighted in the loan list.
                        </div>
                    </div>
                </div>
            </div>

            <div class="mb-3">
                <div class="d-flex align-items-start">
                    <div class="me-2" style="color:#8b5cf6;">
                        <i class="bi bi-arrow-counterclockwise"></i>
                    </div>
                    <div>
                        <div style="font-size: 13px; font-weight:600; color:#072F1F;">Return process</div>
                        <div class="text-muted" style="font-size:12px;">
                            Use the <strong>Returns</strong> menu to process the loan return.
                        </div>
                    </div>
                </div>
            </div>

            <div class="mt-auto pt-3 border-top">
                <a href="{{ route('peminjaman.index') }}"
                   class="text-decoration-none d-block"
                   style="font-size:13px;color:#072F1F;">
                    <i class="bi bi-arrow-right"></i> View all loans
                </a>
            </div>
        </div>
    </div>
</div>
{{-- END: Form Card --}}

@endsection